name: Build and deploy Node.js app to Azure Web App - theMOG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install

      - name: npm build (optional)
        run: npm run build --if-present

      - name: npm test (optional)
        run: npm run test --if-present
        continue-on-error: true
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8B45000A6EAD4AB39D7DFC1256B629DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60F40178F1234D65878DDB165E86982D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6CB7E5F4E5194B019DF4F2CBFCD878A3 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'theMOG'
          slot-name: 'Production'
          package: .
          
